# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OzLockCon
con_year: 2017
con_date: June 3â€“4th
con_location: Melbourne
email: admin@ozlockcon.com
description: > # this means to ignore newlines until "baseurl:"
  Australia's first conference dedicated to Locksport
tags: Lockpicking, Locksport, Physical Security, Research

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ozlockcon
github_username:  klepas

# Build settings
markdown: kramdown

gems:
  - jekyll-assets
  - bourbon
  - neat
  - bitters

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .ruby-version

assets:
  prefix: "/assets"
  assets:
    - "*.jpg"
    - "*.png"
    - "*.gif"
    - "*.svg"
  sources:
    - _assets/stylesheets
    - _assets/images
  compress:
    css: true
    js: true
  cache: .asset-cache
  digest: true
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

highlighter: rouge
